# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
 
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Running tests
        run: |
          echo Starting the tests:
          mkdir bin
          mkdir lib
          curl https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.5.2/junit-platform-console-standalone-1.5.2.jar -o lib/junit-platform-console-standalone-1.5.2.jar
          javac -d bin/ $(find JFreeChart_A3/src/org/jfree/chart -name "*.java")
          javac -d bin/ $(find JFreeChart_A3/src/org/jfree/data -name "*.java")
          javac -d bin -cp bin:lib/junit-platform-console-standalone-1.5.2.jar $(find JFreeeChart_A3/Test/ -name "*.java")
          java -jar lib/junit-platform-console-standalone-1.5.2.jar --class-path bin --scan-class-path
